### ISSUE TITLE
"date" attribute && locale

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/parsepage#3]
To implement multilingual months' names in dates like this:
 
en | ru | uk
------------ | ------------- | -------------
![image](https://user-images.githubusercontent.com/35847544/35768966-75fc6be6-090c-11e8-85d7-3573bfae3509.png) | ![image](https://user-images.githubusercontent.com/35847544/35768970-848c6954-090c-11e8-94bd-912bb6ed0b49.png)  |  ![image](https://user-images.githubusercontent.com/35847544/35768977-b7496fcc-090c-11e8-8da6-e7260edf41a3.png)

I had to do:

`<~day> <~/site/common/date/mon.sel selvalue="month"> <~year>`

instead of simple

`<~datetime date="d M Y">`

PHP has:

http://php.net/manual/en/function.strftime.php
http://php.net/manual/en/function.setlocale.php

but it's useless because of:

> **Warning** The locale information is maintained per process, not per thread. If you are running PHP on a multithreaded server API like IIS, HHVM or Apache on Windows, you may experience sudden changes in locale settings while a script is running, though the script itself never called setlocale(). This happens due to other scripts running in different threads of the same process at the same time, changing the process-wide locale using setlocale().

There is also:

http://php.net/IntlDateFormatter

Seems too complicated and need `php-intl` extension to be installed.

**Comment by osalabs** [comment]
well, parser only uses date(), I think it's better not to add `php-intl` dependency.

Possible solution would be to implement ability to have custom attribute handlers and ability override default behavior for attributes like `date`. This way developer can create it's own date handler using php-intl or any other solution. But it's out of scope of this issue.
