### ISSUE TITLE
Documentation: Broken link for ASP.NET "date" format

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/parsepage#8]
> date - will format tag value as date, format depends on language: PHP, ASP.NET

**Comment by osalabs** [comment]
Not clear what do you mean here.
Link is works - https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
And there are 3 language-independent values: short, long, sql

**Comment by vladsavchuk** [comment]
It's strange, when I follow the link [https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.80).aspx](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.80).aspx) I see the following page:
![image](https://user-images.githubusercontent.com/35847544/49327223-4736a400-f567-11e8-95ac-4a4e9bb936f0.png)

Most likely some improper geo redirection.

**Comment by osalabs** [comment]
I don't see the link you provided in our code. ParsePage contains link in my comment.

**Comment by vladsavchuk** [comment]
![image](https://user-images.githubusercontent.com/35847544/49339701-41f85880-f63e-11e8-875f-9ea56551c5f7.png)

**Comment by osalabs** [comment]
uhh... this repository contained older version of ParsePage for .NET. Updated to latest.
