### ISSUE TITLE
"select" and values with commas

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/parsepage#9]
I have text values in selects with commas and ampersands:

```html
<option value="Bananas &amp; apples">Bananas &amp; apples</option>
<option value="Furits, vegs, water">Furits, vegs, water</option>
```
Such options are not selected if I pass the value as usual:

`<~select_options select="my_value">`

ParsePage code splits `my_value` by commas. How to avoid this? 
What about ampersands?

I need some attribute option to take "my_value" as is without any further processing.

**Comment by osalabs** [comment]
now you can do `<~select_options select="my_value" multi="">` to disable multi values at all

or `<~select_options select="my_value" multi="SOME_OTHER_DELIMITER">` to use some other delimiter

**Comment by vladsavchuk** [comment]
And what about ampersands in values?

**Comment by vladsavchuk** [comment]
Probably disabled multi functionality should be a default behavior. I suspect that I had to put this **multi=""** for safety in many templates with "select".
